---
- hosts: 'zlstatic0*.openstack.org:zl0*.openstack.org'
  # Do the entire play completely for one host at a time
  serial: 1
  any_errors_fatal: true
  tasks:
    - name: Hard stop zuul-launcher
      shell: 'zuul-launcher stop'
      become: true
      become_user: zuul

    - name: Wait for (3h10m) to stop zuul-launcher
      wait_for:
        path: /var/run/zuul-launcher/zuul-launcher.pid
        state: absent
        timeout: 11400

    - name: Restart zuul-launcher
      service:
        name: zuul-launcher
        state: restarted
      become: true
      become_user: root
