---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - shell: 'openstack quota set openstackzuul --cores 800 --ram 800000 --instances 100'
      environment:
        OS_CLOUD: admin-infracloud-vanilla

    - shell: 'openstack quota set openstackzuul --cores 800 --ram 800000 --instances 100'
      environment:
        OS_CLOUD: admin-infracloud-chocolate
