---
- hosts: "localhost:!disabled"
  connection: local
  gather_facts: false
  tasks:
  - git:
      repo: https://gitlabhost.rtp.raleigh.ibm.com/Y9CM3C756/system-config.git
      dest: /opt/system-config/production
      force: yes
  - shell: ./install_modules.sh
    args:
      chdir: /opt/system-config/production
    when: dry_run is not defined
  - shell: ansible-galaxy install --force -r roles.yaml
    args:
      chdir: /opt/system-config/production
